{
  actor {
    account(id: 3375015) {
      alerts {
        policiesSearch {
          policies {
            incidentPreference
            id
            name
          }
        }
      }
    }
  }
}