{
  customerAdministration {
    authenticationDomains(filter: { organizationId: { eq: "Y" } }) {
      items {
        id
        name
        provisioningType
        authenticationType
      }
    }
  }
}